### PR TITLE
Fix test failures 

### LINKED ISSUE #1091: Fix test failures introduced by #1086

### PR DESCRIPTION
**Pull request by alexle0nte**
This PR fixes #1091

### CODE REVIEW

File: src/metrics/loc.rs [hunk 1]
```diff
@@ -1052,28 +1060,29 @@ mod tests {
...
-                      "cloc_min": 2.0,
-                      "cloc_max": 2.0,
-                      "ploc_min": 7.0,
-                      "ploc_max": 7.0,
-                      "lloc_min": 6.0,
-                      "lloc_max": 6.0,
-                      "blank_min": 1.0,
-                      "blank_max": 1.0
-                    }"###
+                {
```
Comment (marco-c) [inline src/metrics/loc.rs:1063]: Could you keep the same indentation as before to reduce the diff?

File: src/metrics/loc.rs [hunk 2]
```diff
@@ -1099,28 +1108,29 @@ mod tests {
...
-                      "cloc_min": 2.0,
-                      "cloc_max": 2.0,
-                      "ploc_min": 7.0,
-                      "ploc_max": 7.0,
-                      "lloc_min": 6.0,
-                      "lloc_max": 6.0,
-                      "blank_min": 0.0,
-                      "blank_max": 0.0
-                    }"###
+                {
```
Comment (marco-c) [inline src/metrics/loc.rs:1111]: Same here

File: src/metrics/loc.rs [hunk 3]
```diff
@@ -1147,28 +1157,29 @@ mod tests {
...
-                      "cloc_max": 3.0,
-                      "ploc_min": 7.0,
-                      "ploc_max": 7.0,
-                      "lloc_min": 6.0,
-                      "lloc_max": 6.0,
-                      "blank_min": 1.0,
-                      "blank_max": 1.0
-                    }"###
+                {
+                  "sloc": 10.0,
```
Comment (marco-c) [inline src/metrics/loc.rs:1161]: And here

**Review by marco-c — APPROVED** [review]
